### ISSUE TITLE
Crash on clean installation

### ISSUE THREAD

**Issue by haf** [bernd/fpm-cookery#105]
```
bash-4.2$ gem install fpm-cookery
Fetching: systemu-2.6.5.gem (100%)
Successfully installed systemu-2.6.5
Fetching: addressable-2.3.7.gem (100%)
Successfully installed addressable-2.3.7
Fetching: json_pure-1.8.2.gem (100%)
Successfully installed json_pure-1.8.2
Fetching: hiera-1.3.4.gem (100%)
Successfully installed hiera-1.3.4
Fetching: facter-2.4.1.gem (100%)
Successfully installed facter-2.4.1
Fetching: puppet-3.7.5.gem (100%)
Successfully installed puppet-3.7.5
Fetching: fpm-cookery-0.26.1.gem (100%)
Successfully installed fpm-cookery-0.26.1
7 gems installed
bash-4.2$ fpm cook
Missing required -s flag. What package source did you want? {:level=>:warn}
Missing required -t flag. What package output did you want? {:level=>:warn}
Fix the above problems, and you'll be rolling packages in no time! {:level=>:fatal}
bash-4.2$ ^C
bash-4.2$ fpm
fpm       fpm-cook
bash-4.2$ fpm-cook
/home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puppet-3.7.5/lib/puppet/defaults.rb:488: warning: duplicated key at line 489 ignored: :queue_type
/home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puppet-3.7.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>': uninitialized constant Syck (NameError)
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puppet-3.7.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `<module:YAML>'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puppet-3.7.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:132:in `<top (required)>'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puppet-3.7.5/lib/puppet/vendor/require_vendored.rb:4:in `<top (required)>'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puppet-3.7.5/lib/puppet/vendor.rb:40:in `require_libs'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puppet-3.7.5/lib/puppet/vendor.rb:53:in `load_vendored'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puppet-3.7.5/lib/puppet.rb:172:in `<module:Puppet>'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puppet-3.7.5/lib/puppet.rb:29:in `<top (required)>'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fpm-cookery-0.26.1/lib/fpm/cookery/dependency_inspector.rb:1:in `<top (required)>'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fpm-cookery-0.26.1/lib/fpm/cookery/packager.rb:3:in `<top (required)>'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fpm-cookery-0.26.1/lib/fpm/cookery/cli.rb:4:in `<top (required)>'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/builder/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fpm-cookery-0.26.1/bin/fpm-cook:5:in `<top (required)>'
	from /home/builder/.rbenv/versions/2.2.1/bin/fpm-cook:23:in `load'
	from /home/builder/.rbenv/versions/2.2.1/bin/fpm-cook:23:in `<main>'
```

**Comment by bernd** [comment]
Thanks for the report!

**Comment by bernd** [comment]
Looks like Puppet 3.x does not run on Ruby 2.2. :confused: 

https://tickets.puppetlabs.com/browse/PUP-3796

**Comment by bernd** [comment]
The above commits let fpm-cookery run on Ruby 2.2.

Automatic dependency installtion is disabled when running on 2.2.

**Comment by lordnynex** [comment]
Hi @bernd So does this mean downgrading ruby in the build environment is better?
