### ISSUE TITLE
confused about cache dir?

### ISSUE THREAD

**Issue by ITler** [bernd/fpm-cookery#141]
I'm new to fpm-cookery. I've installed today (fpm-cookery v0.31.0 (fpm v1.4.0)) and try to learn from your recipes collection, but can't explain following issue

    $ fpm-cook
    ===> Starting package creation for foo-0.1.0 (ubuntu, deb)
    ===> 
    ===> Verifying build_depends and depends with Puppet
    ===> All build_depends and depends packages installed
    ===> Fetching source: 
    ===> Using cached file /root/test/cache
    /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/source_integrity_check.rb:63:in `read': Is a directory - /root/test/cache (Errno::EISDIR)
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/source_integrity_check.rb:63:in `block in build_checksum'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/source_integrity_check.rb:62:in `open'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/source_integrity_check.rb:62:in `build_checksum'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/source_integrity_check.rb:37:in `verify!'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/source_integrity_check.rb:15:in `initialize'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/packager.rb:90:in `new'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/packager.rb:90:in `block in dispense'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/packager.rb:83:in `chdir'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/packager.rb:83:in `dispense'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/cli.rb:113:in `exec'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/cli.rb:77:in `block in execute'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/book.rb:16:in `call'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/book.rb:16:in `load_recipe'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/cli.rb:73:in `execute'
    	from /var/lib/gems/1.9.1/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
    	from /var/lib/gems/1.9.1/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
    	from /var/lib/gems/1.9.1/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
    	from /var/lib/gems/1.9.1/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
    	from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/bin/fpm-cook:7:in `<top (required)>'
    	from /usr/local/bin/fpm-cook:23:in `load'
    	from /usr/local/bin/fpm-cook:23:in `<main>'

This is my recipe:

    class Foo < FPM::Cookery::Recipe
      description 'foo'

      name     'foo'
      version  '0.1.0'
      revision '1'

      arch     'all'
      section  'main'

     # depends        'openssh-client (>=1.6.6)'

      def build
        # nothing to do here
      end

      def install
        usr('local').install workdir('README.md')
      end
    end

I've just want to package one file (for testing purpose). The mentioned README.md is located in same directory as the recipe.rb (`/root/test`)

What's my mistake here?

**Comment by ITler** [comment]
This was because of missing `source` statement.
